export {
  jobs
} from '../../public/data/job-openings-data.json';
export {
  aboutBlock,
  aboutOrganizerBlock,
  addToHomeScreen,
  blog,
  bookmarked,
  buyTicket,
  coc,
  codeOfConduct,
  dates,
  description,
  emailUs,
  faq,
  featuredVideos,
  feedback,
  filters,
  followOur,
  followUs,
  footer,
  footerRelBlock,
  galleryBlock, image, jobOpenings, latestPostsBlock,
  loading,
  mapBlock,
  mySchedule,
  notifications,
  offlineMessage,
  partnersBlock,
  previousSpeakersBlock,
  refresh, registerClosed, registerNow, registration, schedule,
  serviceWorkerAvailable,
  serviceWorkerError,
  serviceWorkerInstalled,
  serviceWorkerInstalling,
  sessionDetails,
  signIn,
  signInDialog,
  signOut,
  speakerDetails,
  speakers,
  speakersBlock, submitCFP, subscribeBlock, subscribeNote,
  team,
  ticketsBlock,
  timezoneOffset,
  title, toBeAnnounce, viewHighlights, viewPhotos
} from '../../public/data/resources.json';
export {
  contentLoaders,
  dateFormat,
  disabledSchedule,
  hashtag,
  heroSettings,
  location,
  mailto,
  navigation,
  organizer,
  showForkMeBlockForProjectIds,
  signInProviders,
  socialNetwork
} from '../../public/data/settings.json';

